### PR TITLE
Re-fixing #125 

### PR DESCRIPTION
**Pull request by yansh**

### CODE REVIEW

**Comment by dhowe** [comment]
if (page === vAPI.getURL("vault.html") ||
      page === vAPI.getURL("dashboard.html") ||
      page.indexOf("chrome://") === 0 ||
      page.indexOf("about://") === 0) {
      uDom.nodeFromId('pause-button').disabled = true;
      uDom.nodeFromId('resume-button').disabled = true;
    }

**Comment by yansh** [comment]
This doesn't seem to cover the empty page in Firefox, which returns "about:blank"

**Comment by dhowe** [comment]
````js
 if (page === vAPI.getURL("vault.html") ||
      page.indexOf(vAPI.getURL("dashboard.html")) === 0 ||
      page.indexOf("chrome://") === 0 ||
      page.indexOf("about:") === 0) {
      uDom.nodeFromId('pause-button').disabled = true;
      uDom.nodeFromId('resume-button').disabled = true;
    }

**Comment by yansh** [comment]
Yep this should do it. Do you want me update the PR or you will edit it on your side?

**Comment by dhowe** [comment]
go for it

**Pull request merged**
